### ISSUE TITLE
Dependency on couchdb.http not listed

### ISSUE THREAD

**Issue by LourensVeen** [indodutch/sim-city-client#7]
Sim-city-client depends on couchdb.http (see e.g. simcity/actors.py) but it is not listed in requirements.txt. Perhaps you're meant to install it as part of CouchDB (apt-get install python-couchdb)? Or is this an oversight?

**Comment by blootsvoets** [comment]
`CouchDB==1.0.1` is in the `requirements.txt`, and it includes the `couchdb.http` package. Does this result in an error for you? What version of pip and python are you using?

**Comment by LourensVeen** [comment]
Hmm, interesting. I have pip 8.1.2 and Python 2.7.11. I should have copied down the error message, but didn't; I'm pretty sure it was a standard import error though, triggered by running the nosetests.

I've just checked and cannot reproduce the problem, even if I remove the python-couchdb apt package. And this makes sense, since I have CouchDB 1.0.1, including couchdb/http.py, installed in the virtualenv.

So I'm not sure what happened, I guess the most likely explanation is that I messed up something with the virtualenv somehow. Since it works now, I'll close this.

**Comment by blootsvoets** [comment]
Btw: I've had the same problem as you describe in some other projects: if the nosetests command is the global command, and not the one in the virtualenv, it might not detect the packages in the virtualenv. Highly annoying... What should always work is
```
$VIRTUAL_ENV/bin/nosetests
```

**Comment by LourensVeen** [comment]
Ah, that may well have been the issue then. Thanks, learnt something :-).
